version: 0.2

phases:
        install:
                runtime-versions:
                        docker: 19
        pre_build:
                commands: 
                        - echo "Running pipeline!"
                        - yum install wget -y
                        - yum install jq -y
                        - wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.rpm
                        - rpm -ivh ./trivy_0.19.2_Linux-64bit.rpm
                        - /usr/local/bin/trivy --version
                        - echo ${Commit_ID}
                        - echo "test"
        build:
                commands:
                        - echo "Building"
                        - message=$(aws codecommit get-commit --repository-name Trivy-Demo --commit-id ${Commit_ID} | jq .commit.message)
                        - export DOCKER_IMAGE=$(echo $message | grep "::.*" -o | sed 's/^..//' | sed 's/\\n//g' | sed 's/"//g')
                        - echo $DOCKER_IMAGE
                        - cd docker/centos
                        - ls
                        - docker build -t trivy-testing:latest .
                        - echo "Done building1"
        post_build:
                commands:
                        - echo "Done build!"
